name: task-a cd

on: [pull_request]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: |
            pip install -r ./task_a/requirements.txt
        - name: Run pytest
          run: |
            pytest ./task_a/task_a.py
        
        # - name: Cache pip dependencies
        #   uses: actions/cache@v3
        #   with:
        #     path: ~/.npm
        #     key: ${{ runner.OS }}-npm-cache-${{ hashFiles('./requirements.txt') }}
        #     restore-keys: |
        #       ${{ runner.OS }}-npm-cache-
  # TODO artefacts
  # example_matrix:
  #   strategy:
  #     matrix:
  #       version: [10, 12, 14]
  #       os: [ubuntu-latest, windows-latest]

      
